"""empty message

Revision ID: f4972ef423c3
Revises: e63597c30f77
Create Date: 2025-03-10 10:06:07.584286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4972ef423c3'
down_revision = 'e63597c30f77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('operation', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_details', schema=None) as batch_op:
        batch_op.drop_column('operation')

    # ### end Alembic commands ###
